# Generated by Django 4.0.5 on 2022-06-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(default='talca', max_length=255),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(default='talca', max_length=255),
        ),
    ]
