# Generated by Django 4.0.5 on 2022-06-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ciudad_nombre_alter_idioma_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
