# Generated by Django 4.0.4 on 2022-05-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_postgrado_postgradousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgradousuario',
            name='postgrado',
        ),
        migrations.RemoveField(
            model_name='postgradousuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Postgrado',
        ),
        migrations.DeleteModel(
            name='PostgradoUsuario',
        ),
    ]
