# Generated by Django 4.0.5 on 2022-06-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ciudad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ciudad',
        ),
    ]
