# Generated by Django 4.0.4 on 2022-05-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_postgradousuario_postgrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IdiomaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.idioma')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publicacion')),
            ],
        ),
    ]
