# Generated by Django 4.0.5 on 2022-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_genero_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField(max_length=255)),
                ('stock', models.IntegerField(max_length=255)),
                ('genero', models.ManyToManyField(to='app.genero')),
            ],
        ),
    ]
