# Generated by Django 4.0.5 on 2022-06-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_articulo_precio_alter_articulo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='some string', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='idioma',
            field=models.ForeignKey(default='Ingles', on_delete=django.db.models.deletion.CASCADE, to='app.idioma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio_total', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='editorial',
            field=models.ForeignKey(default='Nova', on_delete=django.db.models.deletion.CASCADE, to='app.editorial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ForeignKey(default='Accion', on_delete=django.db.models.deletion.CASCADE, to='app.tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(default='Talca', on_delete=django.db.models.deletion.CASCADE, to='app.ciudad'),
            preserve_default=False,
        ),
    ]
